package com.fiserv.atm.load.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.fiserv.atm.load.cayenne.EntryMenuItem;

/**
 * Class _Account was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Account extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String CODE_PROPERTY = "code";
    @Deprecated
    public static final String NAME_PROPERTY = "name";
    @Deprecated
    public static final String ENTRY_MENU_ITEMS_PROPERTY = "entryMenuItems";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> CODE = new Property<String>("code");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<List<EntryMenuItem>> ENTRY_MENU_ITEMS = new Property<List<EntryMenuItem>>("entryMenuItems");

    public void setCode(String code) {
        writeProperty("code", code);
    }
    public String getCode() {
        return (String)readProperty("code");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToEntryMenuItems(EntryMenuItem obj) {
        addToManyTarget("entryMenuItems", obj, true);
    }
    public void removeFromEntryMenuItems(EntryMenuItem obj) {
        removeToManyTarget("entryMenuItems", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EntryMenuItem> getEntryMenuItems() {
        return (List<EntryMenuItem>)readProperty("entryMenuItems");
    }


}
