package com.fiserv.atm.load.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.fiserv.atm.load.cayenne.Entry;

/**
 * Class _EntryType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EntryType extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String CODE_PROPERTY = "code";
    @Deprecated
    public static final String NAME_PROPERTY = "name";
    @Deprecated
    public static final String ENTRIES_PROPERTY = "entries";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> CODE = new Property<String>("code");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<List<Entry>> ENTRIES = new Property<List<Entry>>("entries");

    public void setCode(String code) {
        writeProperty("code", code);
    }
    public String getCode() {
        return (String)readProperty("code");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToEntries(Entry obj) {
        addToManyTarget("entries", obj, true);
    }
    public void removeFromEntries(Entry obj) {
        removeToManyTarget("entries", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Entry> getEntries() {
        return (List<Entry>)readProperty("entries");
    }


}
