package com.fiserv.atm.load.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.fiserv.atm.load.cayenne.EntryMenuItem;
import com.fiserv.atm.load.cayenne.FeatureMenuItem;

/**
 * Class _EntryMenu was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EntryMenu extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String SCREEN_NUMBER_PROPERTY = "screenNumber";
    @Deprecated
    public static final String ENTRY_MENU_ITEMS_PROPERTY = "entryMenuItems";
    @Deprecated
    public static final String ENTRY_MENU_ITEMS1_PROPERTY = "entryMenuItems1";
    @Deprecated
    public static final String FEATURE_MENU_ITEM_PROPERTY = "featureMenuItem";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> SCREEN_NUMBER = new Property<Integer>("screenNumber");
    public static final Property<List<EntryMenuItem>> ENTRY_MENU_ITEMS = new Property<List<EntryMenuItem>>("entryMenuItems");
    public static final Property<List<EntryMenuItem>> ENTRY_MENU_ITEMS1 = new Property<List<EntryMenuItem>>("entryMenuItems1");
    public static final Property<FeatureMenuItem> FEATURE_MENU_ITEM = new Property<FeatureMenuItem>("featureMenuItem");

    public void setScreenNumber(Integer screenNumber) {
        writeProperty("screenNumber", screenNumber);
    }
    public Integer getScreenNumber() {
        return (Integer)readProperty("screenNumber");
    }

    public void addToEntryMenuItems(EntryMenuItem obj) {
        addToManyTarget("entryMenuItems", obj, true);
    }
    public void removeFromEntryMenuItems(EntryMenuItem obj) {
        removeToManyTarget("entryMenuItems", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EntryMenuItem> getEntryMenuItems() {
        return (List<EntryMenuItem>)readProperty("entryMenuItems");
    }


    public void addToEntryMenuItems1(EntryMenuItem obj) {
        addToManyTarget("entryMenuItems1", obj, true);
    }
    public void removeFromEntryMenuItems1(EntryMenuItem obj) {
        removeToManyTarget("entryMenuItems1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EntryMenuItem> getEntryMenuItems1() {
        return (List<EntryMenuItem>)readProperty("entryMenuItems1");
    }


    public void setFeatureMenuItem(FeatureMenuItem featureMenuItem) {
        setToOneTarget("featureMenuItem", featureMenuItem, true);
    }

    public FeatureMenuItem getFeatureMenuItem() {
        return (FeatureMenuItem)readProperty("featureMenuItem");
    }


}
