package com.fiserv.atm.load.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.fiserv.atm.load.cayenne.Entry;
import com.fiserv.atm.load.cayenne.EntryMenu;
import com.fiserv.atm.load.cayenne.FeatureMenu;

/**
 * Class _EntryMenuItem was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EntryMenuItem extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String SCREEN_POS_PROPERTY = "screenPos";
    @Deprecated
    public static final String SOURCE_PROPERTY = "source";
    @Deprecated
    public static final String VALUE_PROPERTY = "value";
    @Deprecated
    public static final String ENTRY_PROPERTY = "entry";
    @Deprecated
    public static final String ENTRY_MENU_PROPERTY = "entryMenu";
    @Deprecated
    public static final String GOTO_ENTRY_MENU_PROPERTY = "gotoEntryMenu";
    @Deprecated
    public static final String GOTO_FEATURE_MENU_PROPERTY = "gotoFeatureMenu";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> SCREEN_POS = new Property<Integer>("screenPos");
    public static final Property<String> SOURCE = new Property<String>("source");
    public static final Property<String> VALUE = new Property<String>("value");
    public static final Property<Entry> ENTRY = new Property<Entry>("entry");
    public static final Property<EntryMenu> ENTRY_MENU = new Property<EntryMenu>("entryMenu");
    public static final Property<EntryMenu> GOTO_ENTRY_MENU = new Property<EntryMenu>("gotoEntryMenu");
    public static final Property<FeatureMenu> GOTO_FEATURE_MENU = new Property<FeatureMenu>("gotoFeatureMenu");

    public void setScreenPos(Integer screenPos) {
        writeProperty("screenPos", screenPos);
    }
    public Integer getScreenPos() {
        return (Integer)readProperty("screenPos");
    }

    public void setSource(String source) {
        writeProperty("source", source);
    }
    public String getSource() {
        return (String)readProperty("source");
    }

    public void setValue(String value) {
        writeProperty("value", value);
    }
    public String getValue() {
        return (String)readProperty("value");
    }

    public void setEntry(Entry entry) {
        setToOneTarget("entry", entry, true);
    }

    public Entry getEntry() {
        return (Entry)readProperty("entry");
    }


    public void setEntryMenu(EntryMenu entryMenu) {
        setToOneTarget("entryMenu", entryMenu, true);
    }

    public EntryMenu getEntryMenu() {
        return (EntryMenu)readProperty("entryMenu");
    }


    public void setGotoEntryMenu(EntryMenu gotoEntryMenu) {
        setToOneTarget("gotoEntryMenu", gotoEntryMenu, true);
    }

    public EntryMenu getGotoEntryMenu() {
        return (EntryMenu)readProperty("gotoEntryMenu");
    }


    public void setGotoFeatureMenu(FeatureMenu gotoFeatureMenu) {
        setToOneTarget("gotoFeatureMenu", gotoFeatureMenu, true);
    }

    public FeatureMenu getGotoFeatureMenu() {
        return (FeatureMenu)readProperty("gotoFeatureMenu");
    }


}
