package com.fiserv.atm.load.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.fiserv.atm.load.cayenne.EntryMenuItem;
import com.fiserv.atm.load.cayenne.FeatureMenuItem;
import com.fiserv.atm.load.cayenne.Load;
import com.fiserv.atm.load.cayenne.Stream;

/**
 * Class _FeatureMenu was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FeatureMenu extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String SCREEN_NUMBER_PROPERTY = "screenNumber";
    @Deprecated
    public static final String ENTRY_MENU_ITEMS_PROPERTY = "entryMenuItems";
    @Deprecated
    public static final String FEATURE_MENU_ITEMS_PROPERTY = "featureMenuItems";
    @Deprecated
    public static final String LOAD_PROPERTY = "load";
    @Deprecated
    public static final String STREAM_PROPERTY = "stream";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> SCREEN_NUMBER = new Property<Integer>("screenNumber");
    public static final Property<List<EntryMenuItem>> ENTRY_MENU_ITEMS = new Property<List<EntryMenuItem>>("entryMenuItems");
    public static final Property<List<FeatureMenuItem>> FEATURE_MENU_ITEMS = new Property<List<FeatureMenuItem>>("featureMenuItems");
    public static final Property<Load> LOAD = new Property<Load>("load");
    public static final Property<Stream> STREAM = new Property<Stream>("stream");

    public void setScreenNumber(Integer screenNumber) {
        writeProperty("screenNumber", screenNumber);
    }
    public Integer getScreenNumber() {
        return (Integer)readProperty("screenNumber");
    }

    public void addToEntryMenuItems(EntryMenuItem obj) {
        addToManyTarget("entryMenuItems", obj, true);
    }
    public void removeFromEntryMenuItems(EntryMenuItem obj) {
        removeToManyTarget("entryMenuItems", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EntryMenuItem> getEntryMenuItems() {
        return (List<EntryMenuItem>)readProperty("entryMenuItems");
    }


    public void addToFeatureMenuItems(FeatureMenuItem obj) {
        addToManyTarget("featureMenuItems", obj, true);
    }
    public void removeFromFeatureMenuItems(FeatureMenuItem obj) {
        removeToManyTarget("featureMenuItems", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FeatureMenuItem> getFeatureMenuItems() {
        return (List<FeatureMenuItem>)readProperty("featureMenuItems");
    }


    public void setLoad(Load load) {
        setToOneTarget("load", load, true);
    }

    public Load getLoad() {
        return (Load)readProperty("load");
    }


    public void setStream(Stream stream) {
        setToOneTarget("stream", stream, true);
    }

    public Stream getStream() {
        return (Stream)readProperty("stream");
    }


}
