package com.fiserv.atm.load.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.fiserv.atm.load.cayenne.FeatureMenuItem;
import com.fiserv.atm.load.cayenne.Flavor;

/**
 * Class _Feature was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Feature extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String ACTIVE_PROPERTY = "active";
    @Deprecated
    public static final String CODE_PROPERTY = "code";
    @Deprecated
    public static final String NAME_PROPERTY = "name";
    @Deprecated
    public static final String FEATURE_MENU_ITEMS_PROPERTY = "featureMenuItems";
    @Deprecated
    public static final String FLAVORS_PROPERTY = "flavors";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Boolean> ACTIVE = new Property<Boolean>("active");
    public static final Property<String> CODE = new Property<String>("code");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<List<FeatureMenuItem>> FEATURE_MENU_ITEMS = new Property<List<FeatureMenuItem>>("featureMenuItems");
    public static final Property<List<Flavor>> FLAVORS = new Property<List<Flavor>>("flavors");

    public void setActive(boolean active) {
        writeProperty("active", active);
    }
	public boolean isActive() {
        Boolean value = (Boolean)readProperty("active");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setCode(String code) {
        writeProperty("code", code);
    }
    public String getCode() {
        return (String)readProperty("code");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToFeatureMenuItems(FeatureMenuItem obj) {
        addToManyTarget("featureMenuItems", obj, true);
    }
    public void removeFromFeatureMenuItems(FeatureMenuItem obj) {
        removeToManyTarget("featureMenuItems", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FeatureMenuItem> getFeatureMenuItems() {
        return (List<FeatureMenuItem>)readProperty("featureMenuItems");
    }


    public void addToFlavors(Flavor obj) {
        addToManyTarget("flavors", obj, true);
    }
    public void removeFromFlavors(Flavor obj) {
        removeToManyTarget("flavors", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Flavor> getFlavors() {
        return (List<Flavor>)readProperty("flavors");
    }


}
