package com.fiserv.atm.load.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.fiserv.atm.load.cayenne.Feature;
import com.fiserv.atm.load.cayenne.FeatureMenuItem;

/**
 * Class _Flavor was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Flavor extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String NAME_PROPERTY = "name";
    @Deprecated
    public static final String FEATURE_PROPERTY = "feature";
    @Deprecated
    public static final String FEATURE_MENU_ITEMS_PROPERTY = "featureMenuItems";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<Feature> FEATURE = new Property<Feature>("feature");
    public static final Property<List<FeatureMenuItem>> FEATURE_MENU_ITEMS = new Property<List<FeatureMenuItem>>("featureMenuItems");

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setFeature(Feature feature) {
        setToOneTarget("feature", feature, true);
    }

    public Feature getFeature() {
        return (Feature)readProperty("feature");
    }


    public void addToFeatureMenuItems(FeatureMenuItem obj) {
        addToManyTarget("featureMenuItems", obj, true);
    }
    public void removeFromFeatureMenuItems(FeatureMenuItem obj) {
        removeToManyTarget("featureMenuItems", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FeatureMenuItem> getFeatureMenuItems() {
        return (List<FeatureMenuItem>)readProperty("featureMenuItems");
    }


}
