package com.fiserv.atm.load.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.fiserv.atm.load.cayenne.FeatureMenu;

/**
 * Class _Load was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Load extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String DESCRIPTION_PROPERTY = "description";
    @Deprecated
    public static final String TYPE_PROPERTY = "type";
    @Deprecated
    public static final String FEATURE_MENUS_PROPERTY = "featureMenus";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> DESCRIPTION = new Property<String>("description");
    public static final Property<String> TYPE = new Property<String>("type");
    public static final Property<List<FeatureMenu>> FEATURE_MENUS = new Property<List<FeatureMenu>>("featureMenus");

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }

    public void addToFeatureMenus(FeatureMenu obj) {
        addToManyTarget("featureMenus", obj, true);
    }
    public void removeFromFeatureMenus(FeatureMenu obj) {
        removeToManyTarget("featureMenus", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FeatureMenu> getFeatureMenus() {
        return (List<FeatureMenu>)readProperty("featureMenus");
    }


}
